### ISSUE TITLE
Inkplate 6 Plus wakes up on touch with the wrong wakeup_reason

### ISSUE THREAD

**Issue by jonasBer** [SolderedElectronics/Inkplate-Arduino-library#252]
Hello,

I am using the example: examples/Inkplate6PLUS/Advanced/DeepSleep/Inkplate6PLUS_Wake_Up_On_Touchscreen,
and when it wakes up on touch, I get the reason ESP_SLEEP_WAKEUP_EXT0.

I think the correct reason should be ESP_SLEEP_WAKEUP_TOUCHPAD.

I need to distinguish between the two options.

Can you check this?

Thank you,
Jonas

**Comment by rsoric** [comment]
Hi Jonas, 

really sorry this wasn't addressed in time, this was left in our ticketing system's backlog for a while.

The reason why wake up on touchscreen wakes up with EXT0 is because it's connected via an ESP32 pin - WAKEUP_TOUCHPAD is ESP32 labeling for certain devices which have a touchpad on another specific pin, we use EXT0 for the touchscreen. So, you're getting the correct value. Hope that helps clear things up.

-Rob
