### ISSUE TITLE
OTA update?

### ISSUE THREAD

**Issue by tboerstad** [SolderedElectronics/Inkplate-Arduino-library#253]
Are there any technical blockers for OTA update of the Inkplate devices? 

An OTA arduino sketch would be an awesome example to have

**Comment by rsoric** [comment]
Hi @tboerstad ,

we haven't experimented with it, but yes, it should work. You will have to change the partition scheme to one that supports OTA (the default in the Inkplate board def is one which does NOT support OTA, so change that). There should be enough memory for everything else in the Inkplate library alongside OTA.

Check [this](https://randomnerdtutorials.com/esp32-over-the-air-ota-programming/) tutorial out for OTA, because it's the same chip it should work just fine on Inkplate. If we were to write an example, it would essentially have the same info.

I've also forwarded your suggestion for an OTA example to our R&D team. Please let me know if you run into issues when using OTA on Inkplate

-Rob
