### ISSUE TITLE
Workaround possible for 3bit partialUpdates?

### ISSUE THREAD

**Issue by pimlie** [SolderedElectronics/Inkplate-Arduino-library#254]
Afaik 3bit partial updates are not supported due to lack of memory, as the ESP does not have enough memory to keep both the previous buffer as the new buffer in memory (please correct me if Im wrong). So I was wondering if it would be possible to support 3bit partial updates by moving the 'compare' logic outside of inkplate, f.e. using ImageMagick's compare util?

```bash
# create mask with differences
$ compare current.png update.png -compose over -highlight-color White -lowlight-color Black update-mask.png

# then extract the updated pixels into a new image
$ convert update.png update-mask.png -compose CopyOpacity -composite update-difference.png
```

Then update the display with the `update-difference.png` image while ignoring any alpha=0 pixels?

It seems not possible atm as `display.display()` is still clearing the buffer regardless if you call `display.clearDisplay()` yourself or not?

**Comment by rsoric** [comment]
@BornaBiro please have a look at this

**Comment by BornaBiro** [comment]
Hello @pimlie!

Amount of memory is not the main problem with the ESP32 and 3bit partial updates, main problem is the speed and framerate. In order to get good looking partial update on 3 bit mode, it's very important get the same framerate as on 3 bit full refresh. But due additional calculations this is not 100% possible on ESP32.

`display.clearDisplay()` as mentioned in [examples ](https://github.com/SolderedElectronics/Inkplate-Arduino-library/blob/master/examples/Inkplate6/Basic/Inkplate6_Grayscale/Inkplate6_Grayscale.ino#L38 )and [documentation](https://inkplate.readthedocs.io/en/latest/arduino.html#inkplate-cleardisplay) does not clears image on the screen, it clears the image from the framebuffer inside ESP32. Even if you modify the code inside display3() skip the display clean, it sill won't display partial update properly since there is no skip pixel command in the 3 bit waveform.

For now, partial updates on 3 bit are not possible. There are workarounds around that, but this can lead to screen damage.

**Comment by rsoric** [comment]
@pimlie I'll take over from now on, Inkplate 6MOTION is coming out soon, which will have 11fps partial updates, which should be quite fast, and it's based on STM32. Check out the full specs [here](https://www.crowdsupply.com/soldered/inkplate-6-motion).

**Comment by rsoric** [comment]
It's unavoidable for the e-Ink models which we use, they are required to be fully updated at least every once in a while to retain picture quality. Apparently, there are models of e-Ink screens which can only be partially updated but we don't have one like that for any Inkplate model.

Maybe updating partially in 1bit mode and using a dithered image would suffice?
